# Generated by Django 4.1.4 on 2022-12-18 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('mobile_provider_prefix', models.CharField(max_length=3, verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=30, verbose_name='Тег')),
                ('time_zone', models.CharField(blank=True, max_length=35, null=True, verbose_name='Тег клиента (фильтр)')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(verbose_name='Дата и время запуска рассылки')),
                ('stop_at', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
                ('message', models.CharField(max_length=300, verbose_name='Текст сообщения')),
                ('mobile_provider_prefix', models.CharField(max_length=3, verbose_name='Код мобильного оператора клиента (фильтр)')),
                ('tag', models.CharField(blank=True, max_length=30, null=True, verbose_name='Тег клиента (фильтр)')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания записи (отправки)')),
                ('status', models.CharField(choices=[('pending', 'В очереди на отправку'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('timed_out', 'Не успели отправить')], max_length=20, verbose_name='Статус сообщения')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='notificator.customer')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='notificator.notification')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'db_table': 'message',
            },
        ),
    ]
