# Generated by Django 4.1.4 on 2022-12-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time_zone',
            field=models.CharField(default='Moscow', max_length=32, verbose_name='Часовой пояс'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания (отправки)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='notificator.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='notificator.notification', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди на отправку'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки'), ('timed_out', 'Не успели отправить')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='tag',
            field=models.CharField(default='Python', max_length=30, verbose_name='Тег клиента (фильтр)'),
            preserve_default=False,
        ),
    ]
