# Generated by Django 4.1.4 on 2022-12-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notificator', '0003_alter_customer_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notificator.customer', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='message',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notificator.notification', verbose_name='Рассылка'),
        ),
    ]
